import { User, JobListing, Application, JobSeekerProfile } from './types';

export const DEMO_CREDENTIALS = {
  admin: {
    email: 'admin@nextindia.demo',
    password: 'demo123password',
    phone: '9000000001',
    formattedPhone: '+919000000001',
    role: 'admin' as const,
    name: 'Super Admin Portal',
  },
  employer: {
    email: 'employer@nextindia.demo',
    password: 'demo123password',
    phone: '9000000002',
    formattedPhone: '+919000000002',
    role: 'employer' as const,
    name: 'Senthil Kumar (Tech & Apparel Corp)',
    companyName: 'Royal Solutions & Apparel Ltd',
  },
  worker: {
    email: 'worker@nextindia.demo',
    password: 'demo123password',
    phone: '9000000003',
    formattedPhone: '+919000000003',
    role: 'job_seeker' as const,
    category: 'Worker' as const,
    name: 'Kavitha Murugesan',
    designation: 'Sewing Machine Operator',
  },
  staff: {
    email: 'staff@nextindia.demo',
    password: 'demo123password',
    phone: '9000000004',
    formattedPhone: '+919000000004',
    role: 'job_seeker' as const,
    category: 'Staff' as const,
    name: 'Karthik Raja',
    designation: 'Software Developer / Intern',
  },
};

export const DEMO_USERS_DATA: Record<string, Partial<User>> = {
  admin: {
    role: 'admin',
    name: 'Super Admin Portal',
    phone: '+919000000001',
    email: 'admin@nextindia.demo',
    status: 'approved',
    signupStatus: 'completed',
    onboarded: true,
    location: 'Central Hub',
    memberSince: '2026',
  },
  employer: {
    role: 'employer',
    name: 'Senthil Kumar',
    phone: '+919000000002',
    email: 'employer@nextindia.demo',
    status: 'approved',
    signupStatus: 'completed',
    onboarded: true,
    contactPersonName: 'Senthil Kumar',
    fullAddress: 'Plot 45, Industrial & Tech Park',
    area: 'Central Zone',
    location: 'Central Zone',
    latitude: 11.0825,
    longitude: 77.3488,
    gst: '33AAAAA0000A1Z5',
    establishedYear: '2012',
    postCredits: 15,
    totalPurchased: 20,
    totalUsed: 5,
    welcomeOfferClaimed: true,
    memberSince: '2026',
    companyLogoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=150&auto=format&fit=crop&q=80',
    subscription: {
      activePlanId: 'growth_plan',
      price: 2999,
      expiryDate: '2026-12-31',
      planHistory: []
    }
  },
  worker: {
    role: 'job_seeker',
    category: 'Worker',
    name: 'Kavitha Murugesan',
    phone: '+919000000003',
    email: 'worker@nextindia.demo',
    status: 'approved',
    signupStatus: 'completed',
    onboarded: true,
    department: 'Stitching / Sewing',
    designation: 'Sewing Machine Operator',
    location: 'South District',
    latitude: 11.1085,
    longitude: 77.3411,
    memberSince: '2026',
    gender: 'female',
    age: 28,
  },
  staff: {
    role: 'job_seeker',
    category: 'Staff',
    name: 'Karthik Raja',
    phone: '+919000000004',
    email: 'staff@nextindia.demo',
    status: 'approved',
    signupStatus: 'completed',
    onboarded: true,
    department: 'ERP/EDP',
    designation: 'Software Developer / Intern',
    location: 'North District',
    latitude: 11.1120,
    longitude: 77.3510,
    memberSince: '2026',
    gender: 'male',
    age: 23,
  }
};

export const DEMO_SEEKER_PROFILES: Record<'worker' | 'staff', JobSeekerProfile> = {
  worker: {
    userId: 'worker_uid',
    category: 'Worker',
    department: 'Stitching / Sewing',
    designation: 'Sewing Machine Operator',
    experience: 5,
    expectedSalary: 18000,
    workType: 'Shift',
    accommodationNeeded: true,
    foodRequired: true,
    digitalResume: {
      personal: {
        fullName: 'Kavitha Murugesan',
        gender: 'female',
        dob: '1998-05-14',
        age: '28',
        languages: ['Tamil', 'English'],
        location: 'Avinashi Road, Tirupur',
        mobile: '+919000000003',
        hasTwoWheeler: true,
        certificationAccepted: true
      },
      academic: [
        { education: '10th Standard', degree: 'SSLC', institute: 'Government High School Tirupur', year: '2014' }
      ],
      professional: {
        totalExperience: '5 Years',
        noticePeriod: 'Immediate',
        coreSkills: ['Overlock Machine', 'Flatlock Stitching', 'Knitwear Assembly', 'Speed Sewing'],
        complianceKnowledge: ['Factory Safety', 'Needle Guard Standard'],
        previousBrands: 'Dixcy Scott, Dollar Club',
        lastSalary: '₹16,500 / month',
        expectedSalary: '₹18,500 / month'
      },
      recentCompany: [
        { name: 'TexFit Knitwear', position: 'Senior Stitcher', startDate: '2021-01', endDate: '2026-06' }
      ],
      references: []
    }
  },
  staff: {
    userId: 'staff_uid',
    category: 'Staff',
    department: 'Merchandising & Sales',
    designation: 'Senior Garment Merchandiser',
    experience: 8,
    expectedSalary: 45000,
    workType: 'Full-time',
    accommodationNeeded: false,
    foodRequired: false,
    digitalResume: {
      personal: {
        fullName: 'Karthik Raja',
        gender: 'male',
        dob: '1994-08-20',
        age: '32',
        languages: ['Tamil', 'English', 'Hindi'],
        location: 'KPN Colony, Tirupur',
        mobile: '+919000000004',
        hasTwoWheeler: true,
        certificationAccepted: true
      },
      academic: [
        { education: 'Degree', degree: 'B.Sc Textile Fashion & Apparel', institute: 'NIFT TEA Tirupur', year: '2016' }
      ],
      professional: {
        totalExperience: '8 Years',
        noticePeriod: '15 Days',
        coreSkills: ['Buyer Communication', 'Sample Approvals', 'Costing & Tech Packs', 'ERP & Production Tracking', 'Fabric Sourcing'],
        complianceKnowledge: ['BSCI', 'OEKO-TEX Standard 100', 'SEDEX Audit'],
        previousBrands: 'C&A, Decathlon, Primark',
        lastSalary: '₹40,000 / month',
        expectedSalary: '₹48,000 / month'
      },
      recentCompany: [
        { name: 'Poppys Apparels Ltd', position: 'Merchandiser Lead', startDate: '2020-03', endDate: '2026-07' }
      ],
      references: [
        { name: 'R. Sundaram', designation: 'General Manager', company: 'Poppys Apparels', contact: '+919842200000' }
      ]
    }
  }
};

export const DEMO_JOBS_LIST: Partial<JobListing>[] = [
  {
    jobId: 'demo_job_1',
    companyName: 'Royal Exports Tirupur Ltd',
    jobTitle: 'Senior Sewing Machine Operator (Overlock / Flatlock)',
    category: 'Worker',
    department: 'Stitching / Sewing',
    designation: 'Sewing Machine Operator',
    salaryMin: 18000,
    salaryMax: 22000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Veerapandi Industrial Estate, Tirupur',
    latitude: 11.0825,
    longitude: 77.3488,
    openings: 12,
    experienceRequired: 2,
    genderPreference: 'any',
    accommodationProvided: true,
    foodProvided: true,
    shiftTiming: '8:30 AM - 5:30 PM (Shift A)',
    workType: 'Shift',
    description: 'Looking for experienced Sewing Machine Operators skilled in Overlock and Flatlock machines for high-quality export t-shirt assembly. Good incentive structure + free hostel accommodation provided.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 142,
    benefits: {
      esi: true,
      epf: true,
      transport: true,
      bonus: 'Diwali Bonus + Production Incentive',
      teaCash: true,
      accommodation: true,
      food: true,
      overtime_pay: true,
    }
  },
  {
    jobId: 'demo_job_2',
    companyName: 'Royal Exports Tirupur Ltd',
    jobTitle: 'Senior Garment Merchandiser - Knitwear Exports',
    category: 'Staff',
    department: 'Merchandising & Sales',
    designation: 'Senior Garment Merchandiser',
    salaryMin: 40000,
    salaryMax: 50000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Palladam Road, Tirupur',
    latitude: 11.0950,
    longitude: 77.3520,
    openings: 2,
    experienceRequired: 5,
    genderPreference: 'any',
    accommodationProvided: false,
    foodProvided: false,
    shiftTiming: '9:00 AM - 6:30 PM',
    workType: 'Full-time',
    description: 'Require proactive Merchandiser with minimum 5 years in EU/US garment export accounts. Must be expert in costing, T&A submission, yarn to garment tracking, and buyer communication.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 89,
    benefits: {
      esi: true,
      epf: true,
      transport: false,
      bonus: 'Annual Performance Bonus',
      teaCash: true,
      accommodation: false,
      food: false,
      mobile_allowance: true,
      petrol_allowance: true,
    }
  },
  {
    jobId: 'demo_job_3',
    companyName: 'Classic Polo Apparel Group',
    jobTitle: 'Garment Quality Inspector (Inline & Final AQL)',
    category: 'Staff',
    department: 'Quality Control',
    designation: 'Quality Checker',
    salaryMin: 22000,
    salaryMax: 28000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Mangalam Road, Tirupur',
    latitude: 11.1010,
    longitude: 77.3390,
    openings: 4,
    experienceRequired: 3,
    genderPreference: 'any',
    accommodationProvided: true,
    foodProvided: true,
    shiftTiming: '8:00 AM - 5:00 PM',
    workType: 'Shift',
    description: 'Inline and final audit QC staff for knitted garments. Knowledge of 4-point fabric inspection and AQL 2.5 standard essential.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 110,
    benefits: {
      esi: true,
      epf: true,
      transport: true,
      bonus: 'Festival Bonus',
      teaCash: true,
      accommodation: true,
      food: true,
    }
  },
  {
    jobId: 'demo_job_4',
    companyName: 'Armstrong Knitting Mills',
    jobTitle: 'Automatic Cutting Machine Operator & Master',
    category: 'Worker',
    department: 'Cutting',
    designation: 'Cutting Master',
    salaryMin: 25000,
    salaryMax: 32000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Koolipalayam, Tirupur',
    latitude: 11.1320,
    longitude: 77.3210,
    openings: 3,
    experienceRequired: 4,
    genderPreference: 'male',
    accommodationProvided: true,
    foodProvided: true,
    shiftTiming: '8:30 AM - 6:00 PM',
    workType: 'Full-time',
    description: 'Urgent requirement for Cutting Master experienced in Gerber / Lectra CAD automatic cutting table operation for circular knit fabrics.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 65,
    benefits: {
      esi: true,
      epf: true,
      transport: true,
      bonus: 'Production Incentive',
      teaCash: true,
      accommodation: true,
      food: true,
    }
  },
  {
    jobId: 'demo_job_5',
    companyName: 'Eastman Exports Global Ltd',
    jobTitle: 'Maintenance Technician - Sewing & Dyeing Machinery',
    category: 'Staff',
    department: 'Maintenance & Engineering',
    designation: 'Maintenance Technician',
    salaryMin: 28000,
    salaryMax: 35000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Dharapuram Road, Tirupur',
    latitude: 11.0850,
    longitude: 77.3620,
    openings: 2,
    experienceRequired: 4,
    genderPreference: 'male',
    accommodationProvided: true,
    foodProvided: false,
    shiftTiming: 'Rotating Shifts',
    workType: 'Shift',
    description: 'Diploma in Mechanical/Electrical. Responsible for preventive maintenance of Juki/Brother sewing machines and soft flow dyeing vessels.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 78,
    benefits: {
      esi: true,
      epf: true,
      transport: true,
      bonus: 'Annual Bonus',
      teaCash: true,
      accommodation: true,
      food: false,
    }
  },
  {
    jobId: 'demo_job_6',
    companyName: 'Royal Exports Tirupur Ltd',
    jobTitle: 'Ironing & Packing Finishing Helper',
    category: 'Worker',
    department: 'Finishing & Packing',
    designation: 'Ironing Staff',
    salaryMin: 15000,
    salaryMax: 19000,
    salaryBasis: 'Monthly',
    salaryType: 'display_range',
    payoutSchedule: 'Monthly',
    location: 'Veerapandi Industrial Estate, Tirupur',
    latitude: 11.0825,
    longitude: 77.3488,
    openings: 8,
    experienceRequired: 1,
    genderPreference: 'any',
    accommodationProvided: true,
    foodProvided: true,
    shiftTiming: '8:00 AM - 5:00 PM',
    workType: 'Shift',
    description: 'Steam vacuum press ironing and polybag tagging for t-shirts. Freshers welcome to apply.',
    status: 'approved',
    createdAt: new Date().toISOString(),
    views: 130,
    benefits: {
      esi: true,
      epf: true,
      transport: true,
      bonus: 'Attendance Bonus',
      teaCash: true,
      accommodation: true,
      food: true,
    }
  }
];

export const DEMO_APPLICATIONS_LIST: Partial<Application>[] = [
  {
    applicationId: 'demo_app_1',
    jobId: 'demo_job_1',
    jobSeekerId: 'worker_uid',
    employerId: 'employer_uid',
    status: 'shortlisted',
    appliedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    jobTitle: 'Senior Sewing Machine Operator (Overlock / Flatlock)',
    jobCategory: 'Worker',
    department: 'Stitching / Sewing',
    seekerName: 'Kavitha Murugesan',
    experience: '5 Years',
    phone: '+919000000003',
    companyName: 'Royal Exports Tirupur Ltd',
    expectedSalary: '₹18,500 / month',
    preferredInterviewDate: '2026-08-16',
  },
  {
    applicationId: 'demo_app_2',
    jobId: 'demo_job_2',
    jobSeekerId: 'staff_uid',
    employerId: 'employer_uid',
    status: 'applied',
    appliedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    jobTitle: 'Senior Garment Merchandiser - Knitwear Exports',
    jobCategory: 'Staff',
    department: 'Merchandising & Sales',
    seekerName: 'Karthik Raja',
    experience: '8 Years',
    phone: '+919000000004',
    companyName: 'Royal Exports Tirupur Ltd',
    expectedSalary: '₹48,000 / month',
    preferredInterviewDate: '2026-08-18',
  }
];

export const DEMO_DESIGNATIONS_LIST = [
  { name: 'Sewing Machine Operator', category: 'Worker', department: 'Stitching / Sewing' },
  { name: 'Tailor', category: 'Worker', department: 'Stitching / Sewing' },
  { name: 'Quality Checker', category: 'Staff', department: 'Quality Control' },
  { name: 'Cutting Master', category: 'Worker', department: 'Cutting' },
  { name: 'Senior Garment Merchandiser', category: 'Staff', department: 'Merchandising & Sales' },
  { name: 'Maintenance Technician', category: 'Staff', department: 'Maintenance & Engineering' },
  { name: 'Ironing Staff', category: 'Worker', department: 'Finishing & Packing' },
  { name: 'Production Supervisor', category: 'Staff', department: 'Production' },
  { name: 'HR Executive', category: 'Staff', department: 'Administration & HR' },
  { name: 'Pattern Master', category: 'Staff', department: 'CAD & Sampling' },
];
